# Generated by Django 3.1.4 on 2021-02-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patientname',
            field=models.CharField(max_length=50),
        ),
    ]
