# Generated by Django 3.1.4 on 2021-03-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hosp', '0002_auto_20210226_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='prescription',
        ),
    ]
