# Generated by Django 3.1.4 on 2021-03-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosp', '0003_remove_appointment_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('bp', models.CharField(max_length=50)),
                ('phonenuumber', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('medname', models.CharField(max_length=50)),
                ('medmg', models.CharField(max_length=50)),
                ('dose', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
    ]
