# Generated by Django 3.1.4 on 2021-03-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosp', '0004_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='appid',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
