# Generated by Django 3.1.4 on 2021-03-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosp', '0005_prescription_appid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='appid',
            field=models.IntegerField(default='null', max_length=50),
        ),
    ]
