# Generated by Django 3.1.4 on 2021-03-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosp', '0007_auto_20210313_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='appid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appid',
            field=models.IntegerField(default='null'),
        ),
    ]
